### ISSUE TITLE
关于变长预测

### ISSUE THREAD

**Issue by lawsonxwl** [BADBADBADBOY/OCR-TextRecog#2]
狠棒的工作
求问大佬什么时候可以复现一个svtr-lcnet？（支持变长预测的svtr，目前ppocrv3里已经上了）
再一个就是如果设定的输入图片宽度比较大的话 eg 32x280 输入宽度窄的图片时做padding会影响识别性能吗

**Comment by BADBADBADBOY** [comment]
> 狠棒的工作 求问大佬什么时候可以复现一个svtr-lcnet？（支持变长预测的svtr，目前ppocrv3里已经上了） 再一个就是如果设定的输入图片宽度比较大的话 eg 32x280 输入宽度窄的图片时做padding会影响识别性能吗

一般来说，你训练的时候正常因该是保持图片长宽比的，所以在训练的时候，也是通过padding 来达到32*280，所以测试的时候padding不太会影响识别性能，或者你直接不用padding也是可以识别的，因为对于svtr来说 也是个不定长识别的，
